// ─────────────────────────────────────────────────────────────────────────────
//  TOPAS Parameter Database  (v2 — expanded from reference + default_parameters.html)
// ─────────────────────────────────────────────────────────────────────────────

export interface TopasParam {
  key: string;           // e.g. "Ge/{Name}/HLX"  or exact "Ts/Seed"
  type: string;          // d, u, i, b, s, dv, uv, iv, sv, bv
  description: string;
  units?: string;
  defaultValue?: string;
  allowedValues?: string[];
  namespace: string;
}

export const UNIT_GROUPS: Record<string, string[]> = {
  Length:   ["m", "cm", "mm", "um", "nm", "km", "angstrom"],
  Angle:    ["deg", "rad", "mrad"],
  Energy:   ["eV", "keV", "MeV", "GeV", "TeV"],
  Time:     ["s", "ms", "us", "ns", "ps"],
  Density:  ["g/cm3", "kg/m3", "mg/cm3"],
  Dose:     ["gray", "Gy", "mGy", "pGy"],
  Activity: ["Bq", "kBq", "MBq", "GBq"],
  Field:    ["tesla", "gauss"],
};
export const ALL_UNITS = Object.values(UNIT_GROUPS).flat();

export const PHYSICS_MODULES = [
  "g4em-standard_opt0","g4em-standard_opt1","g4em-standard_opt2",
  "g4em-standard_opt3","g4em-standard_opt4",
  "g4em-livermore","g4em-penelope","g4em-lowep","g4em-polarized",
  "g4h-phy_QGSP_BIC_HP","g4h-phy_QGSP_BIC","g4h-phy_FTFP_BERT",
  "g4h-elastic_HP","g4h-elastic",
  "g4decay","g4radioactivedecay",
  "g4ion-binarycascade","g4ion-inclxx",
  "g4stopping",
  "Transportation_Only",
];

export const PARTICLES = [
  "proton","e-","e+","gamma","neutron","alpha","deuteron",
  "triton","He3","GenericIon","pi+","pi-","pi0","mu+","mu-",
  "nu_e","anti_nu_e",
];

export const SCORER_QUANTITIES = [
  "DoseToMedium","DoseToWater","EnergyDeposit",
  "Fluence","SurfaceFluence","SurfaceTrackCount",
  "TrackLengthInVolume","TrackLengthEstimator","PhaseSpace","StepCount",
  "KineticEnergyAtSurface","MomentumDirectionAtSurface",
  "ChargeAtSurface","OriginCount","ProtonLET",
];

export const TOPAS_COLORS = [
  "white","silver","gray","black","red","maroon","yellow","olive",
  "lime","green","aqua","teal","blue","navy","fuchsia","purple",
  "brown","grass","grey","indigo","lightblue","magenta","orange",
  "pink","skyblue","violet",
];

export const DRAWING_STYLES = ["Solid","WireFrame","FullWireFrame","Cloud"];

export const GEOMETRY_TYPES = [
  "TsBox","TsSphere","TsCylinder","Group",
  "G4Orb","G4Torus","G4Cons","G4Para","G4Trd","G4RTrap","G4GTrap",
  "G4EllipticalTube","G4Ellipsoid","G4EllipticalCone","G4Paraboloid",
  "G4Hype","G4Tet","G4TwistedTubs","G4HPolycone","G4SPolycone",
  "G4GenericPolycone","G4HPolyhedra","G4SPolyhedra","G4ExtrudedSolid",
  "G4CutTubs","TsJaws","TsDivergingMLC","TsRangeModulator",
  "TsScatterer1","TsScatterer2",
];

export const COMMON_MATERIALS = [
  "Vacuum","Air",
  "G4_WATER","G4_AIR","G4_ALUMINUM","G4_Fe","G4_Cu","G4_W","G4_Pb",
  "G4_Au","G4_Si","G4_Ti","G4_MYLAR","G4_KAPTON","G4_LUCITE",
  "G4_POLYETHYLENE","G4_NYLON-6","G4_PLEXIGLASS",
  "G4_Ir","G4_Pd",
  "G4_TISSUE-SOFT_ICRP","G4_TISSUE_SOFT_ICRP","G4_BONE_CORTICAL_ICRP",
  "G4_LUNG_ICRP","G4_BRAIN_ICRP","G4_MUSCLE_WITH_SUCROSE",
  "G4_CONCRETE","G4_GLASS_LEAD","G4_STAINLESS-STEEL","G4_I",
];

// Default component suggestions per namespace (for autocomplete after Ns/)
export const NS_DEFAULT_COMPONENTS: Record<string, string[]> = {
  Ge: ["World"],
  Gr: ["View","ViewA"],
  Ph: ["Default"],
  Ts: [],    // Ts/ has no component layer
  Sc: [],
  So: [],
  Ma: [],
  Vr: [],
  Tf: [],
};

// ─────────────────────────────────────────────────────────────────────────────
//  FULL PARAMETER DATABASE
// ─────────────────────────────────────────────────────────────────────────────
export const TOPAS_PARAMS: TopasParam[] = [

  // ── Ts/ ──────────────────────────────────────────────────────────────────
  { key:"Ts/Seed", type:"i", namespace:"Ts",
    description:"Random number generator seed. Use a fixed integer for reproducible runs.",
    defaultValue:"1" },
  { key:"Ts/NumberOfThreads", type:"i", namespace:"Ts",
    description:"Number of CPU threads. 0 = use all available threads.",
    defaultValue:"1" },
  { key:"Ts/ShowHistoryCountAtInterval", type:"i", namespace:"Ts",
    description:"Print a progress line every N histories.",
    defaultValue:"1" },
  { key:"Ts/PauseBeforeQuit", type:"b", namespace:"Ts",
    description:"Keep the OpenGL window open after the run ends.",
    defaultValue:"False" },
  { key:"Ts/PauseBeforeInit", type:"b", namespace:"Ts",
    description:"Pause before Geant4 initialisation (useful for interactive debugging).",
    defaultValue:"False" },
  { key:"Ts/PauseBeforeSequence", type:"b", namespace:"Ts",
    description:"Pause before the run sequence starts.",
    defaultValue:"False" },
  { key:"Ts/UseQt", type:"b", namespace:"Ts",
    description:"Enable the Qt graphical interface for interactive visualisation.",
    defaultValue:"False" },
  { key:"Ts/ShowCPUTime", type:"b", namespace:"Ts",
    description:"Print total CPU time used at the end of the simulation.",
    defaultValue:"True" },
  { key:"Ts/DumpParameters", type:"b", namespace:"Ts",
    description:"Write an HTML file listing ALL parameters (defaults + user-set).",
    defaultValue:"True" },
  { key:"Ts/DumpNonDefaultParameters", type:"b", namespace:"Ts",
    description:"Write an HTML file listing only parameters that differ from TOPAS defaults.",
    defaultValue:"False" },
  { key:"Ts/TrackingVerbosity", type:"i", namespace:"Ts",
    description:"Geant4 tracking verbosity. 0=silent, 1=per-event, 2=per-step, 5=full debug.",
    defaultValue:"0" },
  { key:"Ts/RunVerbosity", type:"i", namespace:"Ts",
    description:"Geant4 run manager verbosity level.",
    defaultValue:"0" },
  { key:"Ts/EventVerbosity", type:"i", namespace:"Ts",
    description:"Geant4 event verbosity level.",
    defaultValue:"0" },
  { key:"Ts/SequenceVerbosity", type:"i", namespace:"Ts",
    description:"Verbosity for the TOPAS run sequence manager.",
    defaultValue:"0" },
  { key:"Ts/MaxStepNumber", type:"i", namespace:"Ts",
    description:"Maximum number of steps per track before it is killed.",
    defaultValue:"1000000" },
  { key:"Ts/NumberOfAnomalousHistoriesToAllowInARow", type:"i", namespace:"Ts",
    description:"How many consecutive anomalous histories are tolerated before aborting.",
    defaultValue:"10000" },
  { key:"Ts/BufferThreadOutput", type:"b", namespace:"Ts",
    description:"Buffer output from individual threads to avoid interleaving.",
    defaultValue:"False" },
  { key:"Ts/ListUnusedParameters", type:"b", namespace:"Ts",
    description:"Print a list of parameters that were defined but never used.",
    defaultValue:"False" },
  { key:"Ts/ExtraSequenceSleepInterval", type:"d", namespace:"Ts",
    units:"Time",
    description:"How long to wait between checks for ExtraSequence files.",
    defaultValue:"10 s" },
  { key:"Ts/ExtraSequenceSleepLimit", type:"d", namespace:"Ts",
    units:"Time",
    description:"Total time to wait for ExtraSequence files before giving up.",
    defaultValue:"36000 s" },
  { key:"Ts/ShowHistoryCountLessFrequentlyAsSimulationProgresses", type:"b", namespace:"Ts",
    description:"Automatically reduce history-count print frequency as the run progresses.",
    defaultValue:"False" },
  { key:"Ts/ShowHistoryCountOnSingleLine", type:"b", namespace:"Ts",
    description:"Keep history-count updates on the same console line (overwrite).",
    defaultValue:"False" },
  { key:"Ts/IncludeTimeInHistoryCount", type:"b", namespace:"Ts",
    description:"Include elapsed time in history-count output.",
    defaultValue:"False" },
  { key:"Ts/LimitConsoleToOneThread", type:"b", namespace:"Ts",
    description:"Only allow thread 0 to write to the console.",
    defaultValue:"False" },

  // ── Ge/ common ────────────────────────────────────────────────────────────
  { key:"Ge/{Name}/Type", type:"s", namespace:"Ge",
    description:"Geometry component type.",
    allowedValues: GEOMETRY_TYPES },
  { key:"Ge/{Name}/Parent", type:"s", namespace:"Ge",
    description:"Name of the parent component. Root of hierarchy is 'World'." },
  { key:"Ge/{Name}/Material", type:"s", namespace:"Ge",
    description:"Material. Use a G4 NIST name (G4_WATER), 'Vacuum', 'Air', or a custom Ma/ material." },
  { key:"Ge/{Name}/TransX", type:"d", namespace:"Ge", units:"Length",
    description:"Translation along X in the parent coordinate system.", defaultValue:"0 m" },
  { key:"Ge/{Name}/TransY", type:"d", namespace:"Ge", units:"Length",
    description:"Translation along Y.", defaultValue:"0 m" },
  { key:"Ge/{Name}/TransZ", type:"d", namespace:"Ge", units:"Length",
    description:"Translation along Z.", defaultValue:"0 m" },
  { key:"Ge/{Name}/RotX", type:"d", namespace:"Ge", units:"Angle",
    description:"Rotation around X (applied after translation).", defaultValue:"0 deg" },
  { key:"Ge/{Name}/RotY", type:"d", namespace:"Ge", units:"Angle",
    description:"Rotation around Y.", defaultValue:"0 deg" },
  { key:"Ge/{Name}/RotZ", type:"d", namespace:"Ge", units:"Angle",
    description:"Rotation around Z.", defaultValue:"0 deg" },
  { key:"Ge/{Name}/Color", type:"s", namespace:"Ge",
    description:"Visualisation colour name.",
    allowedValues: TOPAS_COLORS },
  { key:"Ge/{Name}/DrawingStyle", type:"s", namespace:"Ge",
    description:"Visualisation drawing style.",
    allowedValues: DRAWING_STYLES, defaultValue:"WireFrame" },
  { key:"Ge/{Name}/Invisible", type:"b", namespace:"Ge",
    description:"Hide this volume in the visualisation.", defaultValue:"False" },
  { key:"Ge/{Name}/XBins", type:"i", namespace:"Ge",
    description:"Voxel bins along X. ⚠ Cannot be used if the volume has children." },
  { key:"Ge/{Name}/YBins", type:"i", namespace:"Ge",
    description:"Voxel bins along Y. ⚠ Cannot be used if the volume has children." },
  { key:"Ge/{Name}/ZBins", type:"i", namespace:"Ge",
    description:"Voxel bins along Z. ⚠ Cannot be used if the volume has children." },
  { key:"Ge/{Name}/RBins", type:"i", namespace:"Ge",
    description:"Voxel bins in radial direction (TsCylinder / TsSphere)." },
  { key:"Ge/{Name}/PhiBins", type:"i", namespace:"Ge",
    description:"Voxel bins in phi direction (TsCylinder / TsSphere)." },
  { key:"Ge/{Name}/ThetaBins", type:"i", namespace:"Ge",
    description:"Voxel bins in theta direction (TsSphere)." },
  { key:"Ge/{Name}/IsParallel", type:"b", namespace:"Ge",
    description:"Place this component in a parallel world.", defaultValue:"False" },
  { key:"Ge/{Name}/ParallelWorldName", type:"s", namespace:"Ge",
    description:"Name of the parallel world to host this component." },
  { key:"Ge/{Name}/AssignToRegionNamed", type:"s", namespace:"Ge",
    description:"Assign to a named Geant4 region for region-specific physics." },
  // TsBox
  { key:"Ge/{Name}/HLX", type:"d", namespace:"Ge", units:"Length",
    description:"Half-length along X (TsBox)." },
  { key:"Ge/{Name}/HLY", type:"d", namespace:"Ge", units:"Length",
    description:"Half-length along Y (TsBox)." },
  { key:"Ge/{Name}/HLZ", type:"d", namespace:"Ge", units:"Length",
    description:"Half-length along Z (TsBox or TsCylinder)." },
  // TsSphere / TsCylinder
  { key:"Ge/{Name}/RMin", type:"d", namespace:"Ge", units:"Length",
    description:"Inner radius (0 = solid). TsSphere and TsCylinder.", defaultValue:"0 mm" },
  { key:"Ge/{Name}/RMax", type:"d", namespace:"Ge", units:"Length",
    description:"Outer radius. TsSphere and TsCylinder." },
  { key:"Ge/{Name}/HL", type:"d", namespace:"Ge", units:"Length",
    description:"Half-length along Z (TsCylinder)." },
  { key:"Ge/{Name}/SPhi", type:"d", namespace:"Ge", units:"Angle",
    description:"Starting azimuthal angle phi.", defaultValue:"0 deg" },
  { key:"Ge/{Name}/DPhi", type:"d", namespace:"Ge", units:"Angle",
    description:"Delta azimuthal angle (360 = full revolution).", defaultValue:"360 deg" },
  { key:"Ge/{Name}/STheta", type:"d", namespace:"Ge", units:"Angle",
    description:"Starting polar angle theta (TsSphere).", defaultValue:"0 deg" },
  { key:"Ge/{Name}/DTheta", type:"d", namespace:"Ge", units:"Angle",
    description:"Delta polar angle theta (TsSphere).", defaultValue:"180 deg" },
  // Global Ge/
  { key:"Ge/CheckForOverlaps", type:"b", namespace:"Ge",
    description:"Check for geometry overlaps during construction.", defaultValue:"True" },
  { key:"Ge/CheckForUnusedComponents", type:"b", namespace:"Ge",
    description:"Warn about components defined but never placed.", defaultValue:"True" },
  { key:"Ge/CheckForOverlapsResolution", type:"i", namespace:"Ge",
    description:"Number of test points per volume for overlap checking.", defaultValue:"1000" },
  { key:"Ge/AllowDividedCylinderOrSphereWithParallelWorld", type:"b", namespace:"Ge",
    description:"Allow binned (divided) cylinder/sphere volumes in parallel worlds.", defaultValue:"False" },

  // ── So/ ───────────────────────────────────────────────────────────────────
  { key:"So/{Name}/Type", type:"s", namespace:"So",
    description:"Source type.",
    allowedValues:["Beam","Isotropic","Volumetric","PhaseSpace","Distributed","Environment","Emittance"],
    defaultValue:"Beam" },
  { key:"So/{Name}/Component", type:"s", namespace:"So",
    description:"Reference geometry component for the source position/orientation.",
    defaultValue:"BeamPosition" },
  { key:"So/{Name}/BeamParticle", type:"s", namespace:"So",
    description:"Primary particle species.",
    allowedValues: PARTICLES, defaultValue:"proton" },
  { key:"So/{Name}/BeamEnergy", type:"d", namespace:"So", units:"Energy",
    description:"Nominal kinetic energy of the beam.", defaultValue:"169.23 MeV" },
  { key:"So/{Name}/BeamEnergySpread", type:"u", namespace:"So",
    description:"Fractional energy spread (sigma/E, unitless).", defaultValue:"0.757504" },
  { key:"So/{Name}/NumberOfHistoriesInRun", type:"i", namespace:"So",
    description:"Number of primary particles per run.", defaultValue:"0" },
  { key:"So/{Name}/BeamPositionDistribution", type:"s", namespace:"So",
    description:"Transverse position distribution.",
    allowedValues:["None","Flat","Gaussian"], defaultValue:"Gaussian" },
  { key:"So/{Name}/BeamPositionCutoffShape", type:"s", namespace:"So",
    description:"Shape of the position cutoff.",
    allowedValues:["Ellipse","Rectangle"], defaultValue:"Ellipse" },
  { key:"So/{Name}/BeamPositionCutoffX", type:"d", namespace:"So", units:"Length",
    description:"Cutoff half-width in X for beam position distribution.", defaultValue:"10 cm" },
  { key:"So/{Name}/BeamPositionCutoffY", type:"d", namespace:"So", units:"Length",
    description:"Cutoff half-width in Y for beam position distribution.", defaultValue:"10 cm" },
  { key:"So/{Name}/BeamPositionSpreadX", type:"d", namespace:"So", units:"Length",
    description:"Sigma of Gaussian position distribution in X.", defaultValue:"0.65 cm" },
  { key:"So/{Name}/BeamPositionSpreadY", type:"d", namespace:"So", units:"Length",
    description:"Sigma of Gaussian position distribution in Y.", defaultValue:"0.65 cm" },
  { key:"So/{Name}/BeamAngularDistribution", type:"s", namespace:"So",
    description:"Angular divergence distribution.",
    allowedValues:["None","Flat","Gaussian"], defaultValue:"Gaussian" },
  { key:"So/{Name}/BeamAngularCutoffX", type:"d", namespace:"So", units:"Angle",
    description:"Angular cutoff in X.", defaultValue:"90 deg" },
  { key:"So/{Name}/BeamAngularCutoffY", type:"d", namespace:"So", units:"Angle",
    description:"Angular cutoff in Y.", defaultValue:"90 deg" },
  { key:"So/{Name}/BeamAngularSpreadX", type:"d", namespace:"So", units:"Angle",
    description:"Sigma of Gaussian angular spread in X.", defaultValue:"0.0032 rad" },
  { key:"So/{Name}/BeamAngularSpreadY", type:"d", namespace:"So", units:"Angle",
    description:"Sigma of Gaussian angular spread in Y.", defaultValue:"0.0032 rad" },
  { key:"So/{Name}/BeamEnergySpectrumType", type:"s", namespace:"So",
    description:"Energy spectrum type.",
    allowedValues:["Mono","Discrete","Continuous"] },
  { key:"So/{Name}/BeamEnergySpectrumValues", type:"dv", namespace:"So", units:"Energy",
    description:"Energies for a discrete or continuous spectrum (vector)." },
  { key:"So/{Name}/BeamEnergySpectrumWeights", type:"uv", namespace:"So",
    description:"Relative weights for each energy bin in a discrete spectrum." },
  { key:"So/{Name}/BeamEnergySpectrumWeightsUnscaled", type:"uv", namespace:"So",
    description:"Unscaled weights — multiply by a normalisation factor to get BeamEnergySpectrumWeights." },
  { key:"So/{Name}/ActiveMaterial", type:"s", namespace:"So",
    description:"Material from which primaries are generated (Volumetric source)." },
  { key:"So/{Name}/RecursivelyIncludeChildren", type:"b", namespace:"So",
    description:"Also generate from child volumes made of ActiveMaterial (Volumetric source).",
    defaultValue:"True" },
  { key:"So/{Name}/MaxNumberOfPointsToSample", type:"i", namespace:"So",
    description:"Maximum number of sampling points for the Volumetric source.",
    defaultValue:"1000000" },
  { key:"So/{Name}/NumberOfPointsToSample", type:"i", namespace:"So",
    description:"Alias for MaxNumberOfPointsToSample (older syntax)." },
  { key:"So/{Name}/PhaseSpaceFileName", type:"s", namespace:"So",
    description:"Base name of the phase-space file to read (PhaseSpace source)." },
  { key:"So/{Name}/PhaseSpaceMultipleUse", type:"b", namespace:"So",
    description:"Re-use the phase-space file when it runs out of particles.",
    defaultValue:"True" },
  { key:"So/{Name}/NumberOfSourcePoints", type:"i", namespace:"So",
    description:"Number of fixed emission points (Distributed source)." },
  { key:"So/{Name}/RedistributePointsOnNewRun", type:"b", namespace:"So",
    description:"Re-randomise source points on each new run (Distributed source).",
    defaultValue:"False" },
  { key:"So/{Name}/PointDistribution", type:"s", namespace:"So",
    description:"Spatial distribution of Distributed source points.",
    allowedValues:["Flat","Gaussian"] },
  { key:"So/{Name}/PointDistributionSigma", type:"d", namespace:"So", units:"Length",
    description:"Sigma for Gaussian distribution of Distributed source points." },
  { key:"So/{Name}/Distribution", type:"s", namespace:"So",
    description:"Phase-space distribution type (Emittance source).",
    allowedValues:["BiGaussian","twiss_gaussian","twiss_kv","twiss_waterbag"] },

  // ── Sc/ ───────────────────────────────────────────────────────────────────
  { key:"Sc/{Name}/Quantity", type:"s", namespace:"Sc",
    description:"Observable to score.",
    allowedValues: SCORER_QUANTITIES },
  { key:"Sc/{Name}/Component", type:"s", namespace:"Sc",
    description:"Geometry component to score in." },
  { key:"Sc/{Name}/Surface", type:"s", namespace:"Sc",
    description:"Surface to score on, e.g. 'MyBox/ZPlusSurface'." },
  { key:"Sc/{Name}/OutputFile", type:"s", namespace:"Sc",
    description:"Output filename (without extension)." },
  { key:"Sc/{Name}/OutputType", type:"s", namespace:"Sc",
    description:"Output file format.",
    allowedValues:["csv","binary","ASCII","root","XML","DICOM"] },
  { key:"Sc/{Name}/IfOutputFileAlreadyExists", type:"s", namespace:"Sc",
    description:"What to do if output file already exists.",
    allowedValues:["Overwrite","Increment","Exit"], defaultValue:"Overwrite" },
  { key:"Sc/{Name}/OutputToConsole", type:"b", namespace:"Sc",
    description:"Print results to stdout.", defaultValue:"False" },
  { key:"Sc/{Name}/OutputAfterRun", type:"b", namespace:"Sc",
    description:"Write results after each run (multi-run jobs).", defaultValue:"False" },
  { key:"Sc/{Name}/Report", type:"sv", namespace:"Sc",
    description:"Statistical quantities to include in the output.",
    allowedValues:["Sum","Mean","Variance","Standard_Deviation","Min","Max",
                   "Histories_with_Scorer","Count_in_Bin"] },
  { key:"Sc/{Name}/PropagateToChildren", type:"b", namespace:"Sc",
    description:"Score recursively in child volumes.", defaultValue:"False" },
  { key:"Sc/{Name}/XBins", type:"i", namespace:"Sc",
    description:"Scoring bins along X (overrides geometry bins; preferred when volume has children)." },
  { key:"Sc/{Name}/YBins", type:"i", namespace:"Sc",
    description:"Scoring bins along Y." },
  { key:"Sc/{Name}/ZBins", type:"i", namespace:"Sc",
    description:"Scoring bins along Z." },
  { key:"Sc/{Name}/EBins", type:"i", namespace:"Sc",
    description:"Number of energy bins for energy-binned scoring." },
  { key:"Sc/{Name}/EBinMin", type:"d", namespace:"Sc", units:"Energy",
    description:"Minimum energy for energy-binned scoring." },
  { key:"Sc/{Name}/EBinMax", type:"d", namespace:"Sc", units:"Energy",
    description:"Maximum energy for energy-binned scoring." },
  { key:"Sc/{Name}/EBinEnergy", type:"s", namespace:"Sc",
    description:"Which step energy to use for bin assignment.",
    allowedValues:["PreStep","PostStep","Average"] },
  { key:"Sc/{Name}/OutputBufferSize", type:"i", namespace:"Sc",
    description:"Write buffer size (PhaseSpace scorer).", defaultValue:"1000" },
  { key:"Sc/{Name}/IncludeRunID", type:"b", namespace:"Sc",
    description:"Add RunID column to PhaseSpace output.", defaultValue:"False" },
  { key:"Sc/{Name}/IncludeEventID", type:"b", namespace:"Sc",
    description:"Add EventID column to PhaseSpace output.", defaultValue:"False" },
  { key:"Sc/{Name}/IncludeTrackID", type:"b", namespace:"Sc",
    description:"Add TrackID column to PhaseSpace output.", defaultValue:"False" },
  { key:"Sc/{Name}/IncludeTime", type:"b", namespace:"Sc",
    description:"Add time column to PhaseSpace output.", defaultValue:"False" },
  { key:"Sc/{Name}/IncludeSeed", type:"b", namespace:"Sc",
    description:"Add seed column to PhaseSpace output.", defaultValue:"False" },
  { key:"Sc/{Name}/OnlyIncludeParticlesWithInitialKEAbove", type:"d", namespace:"Sc",
    units:"Energy",
    description:"Only score particles whose initial kinetic energy is above this threshold." },
  { key:"Sc/{Name}/OnlyIncludeParticlesWithInitialKEBelow", type:"d", namespace:"Sc",
    units:"Energy",
    description:"Only score particles whose initial kinetic energy is below this threshold." },
  { key:"Sc/{Name}/OnlyIncludeParticlesNamed", type:"sv", namespace:"Sc",
    description:"Only score particles with these names (e.g. 1 \"gamma\")." },
  { key:"Sc/{Name}/OnlyIncludeParticlesWithCharge", type:"s", namespace:"Sc",
    description:"Only score particles with this charge.",
    allowedValues:["Any","Plus","Minus","Neutral"] },
  { key:"Sc/{Name}/InputFile", type:"s", namespace:"Sc",
    description:"Input data file for scorers that require external data (e.g. TrackLengthEstimator)." },
  { key:"Sc/{Name}/DICOMOutput32BitsPerPixel", type:"b", namespace:"Sc",
    description:"Use 32-bit pixels when writing DICOM output (default is 16-bit).",
    defaultValue:"False" },
  { key:"Sc/AddUnitEvenIfItIsOne", type:"b", namespace:"Sc",
    description:"Always write the unit even when it is 1 (dimensionless).", defaultValue:"False" },
  { key:"Sc/Verbosity", type:"i", namespace:"Sc",
    description:"Verbosity level for the scoring system.", defaultValue:"0" },

  // ── Ph/ ───────────────────────────────────────────────────────────────────
  { key:"Ph/ListName", type:"s", namespace:"Ph",
    description:"Name of the active physics list.", defaultValue:"Default" },
  { key:"Ph/ListProcesses", type:"b", namespace:"Ph",
    description:"Print the process list to the console after initialisation.", defaultValue:"False" },
  { key:"Ph/SetNeutronToStable", type:"b", namespace:"Ph",
    description:"Treat the free neutron as stable (no beta decay).", defaultValue:"False" },
  { key:"Ph/{Name}/Type", type:"s", namespace:"Ph",
    description:"Physics list type.",
    allowedValues:["Geant4_Modular"], defaultValue:"Geant4_Modular" },
  { key:"Ph/{Name}/Modules", type:"sv", namespace:"Ph",
    description:"Geant4 modular physics modules to activate.",
    allowedValues: PHYSICS_MODULES,
    defaultValue:'6 "g4em-standard_opt4" "g4h-phy_QGSP_BIC_HP" "g4decay" "g4ion-binarycascade" "g4h-elastic_HP" "g4stopping"' },
  { key:"Ph/{Name}/EMRangeMin", type:"d", namespace:"Ph", units:"Energy",
    description:"Minimum EM production range cut energy.", defaultValue:"100 eV" },
  { key:"Ph/{Name}/EMRangeMax", type:"d", namespace:"Ph", units:"Energy",
    description:"Maximum EM production range cut energy. Must be ≥ 600 MeV in TOPAS 4.x.",
    defaultValue:"600 MeV" },
  { key:"Ph/{Name}/CutForElectron", type:"d", namespace:"Ph", units:"Length",
    description:"Production cut for electrons in all regions." },
  { key:"Ph/{Name}/CutForGamma", type:"d", namespace:"Ph", units:"Length",
    description:"Production cut for gammas in all regions." },
  { key:"Ph/{Name}/CutForProton", type:"d", namespace:"Ph", units:"Length",
    description:"Production cut for protons in all regions." },
  { key:"Ph/{Name}/Auger", type:"b", namespace:"Ph",
    description:"Enable Auger electron emission.", defaultValue:"False" },
  { key:"Ph/{Name}/AugerCascade", type:"b", namespace:"Ph",
    description:"Enable Auger cascade (requires Auger=True).", defaultValue:"False" },
  { key:"Ph/{Name}/Fluorescence", type:"b", namespace:"Ph",
    description:"Enable atomic fluorescence.", defaultValue:"False" },
  { key:"Ph/{Name}/DeexcitationIgnoreCut", type:"b", namespace:"Ph",
    description:"Ignore production cuts for deexcitation products.", defaultValue:"False" },
  { key:"Ph/{Name}/PIXE", type:"b", namespace:"Ph",
    description:"Enable Particle-Induced X-ray Emission.", defaultValue:"False" },
  { key:"Ph/{Name}/LayeredMassGeometryWorlds", type:"sv", namespace:"Ph",
    description:"List of parallel world names to include as layered mass geometry (for dose-to-medium in implants)." },
  { key:"Ph/{Name}/ForRegion/{Region}/ActiveG4EmModelFromModule", type:"s", namespace:"Ph",
    description:"Override the EM model in a named region (e.g. 'g4em-livermore'). Use with Ge/{Name}/AssignToRegionNamed." },

  // ── Ma/ ───────────────────────────────────────────────────────────────────
  { key:"Ma/{Name}/Components", type:"sv", namespace:"Ma",
    description:"List of element names (e.g. \"Hydrogen\" \"Oxygen\"). Must match Fractions in order." },
  { key:"Ma/{Name}/Fractions", type:"uv", namespace:"Ma",
    description:"Mass fractions corresponding to each element. Must sum to 1." },
  { key:"Ma/{Name}/Density", type:"d", namespace:"Ma", units:"Density",
    description:"Mass density of the material." },
  { key:"Ma/{Name}/DefaultColor", type:"s", namespace:"Ma",
    description:"Default visualisation colour.",
    allowedValues: TOPAS_COLORS },
  { key:"Ma/{Name}/BuildFromMaterials", type:"b", namespace:"Ma",
    description:"Build this material from other TOPAS materials (mixture of materials).",
    defaultValue:"False" },

  // ── Gr/ ───────────────────────────────────────────────────────────────────
  { key:"Gr/{Name}/Type", type:"s", namespace:"Gr",
    description:"Graphics driver.",
    allowedValues:["OpenGL","HepRep","VRML","DAWN","RayTracer","RayTracerX"] },
  { key:"Gr/{Name}/WindowSizeX", type:"i", namespace:"Gr",
    description:"Width of the visualisation window in pixels.", defaultValue:"600" },
  { key:"Gr/{Name}/WindowSizeY", type:"i", namespace:"Gr",
    description:"Height of the visualisation window in pixels.", defaultValue:"600" },
  { key:"Gr/{Name}/WindowPosX", type:"i", namespace:"Gr",
    description:"X screen position of the window.", defaultValue:"0" },
  { key:"Gr/{Name}/WindowPosY", type:"i", namespace:"Gr",
    description:"Y screen position of the window.", defaultValue:"0" },
  { key:"Gr/{Name}/Theta", type:"d", namespace:"Gr", units:"Angle",
    description:"Camera polar angle.", defaultValue:"55 deg" },
  { key:"Gr/{Name}/Phi", type:"d", namespace:"Gr", units:"Angle",
    description:"Camera azimuthal angle.", defaultValue:"20 deg" },
  { key:"Gr/{Name}/Projection", type:"s", namespace:"Gr",
    description:"Camera projection mode.",
    allowedValues:["Perspective","Orthographic"], defaultValue:"Perspective" },
  { key:"Gr/{Name}/PerspectiveAngle", type:"d", namespace:"Gr", units:"Angle",
    description:"Field-of-view angle for perspective projection.", defaultValue:"30 deg" },
  { key:"Gr/{Name}/Zoom", type:"u", namespace:"Gr",
    description:"Zoom factor (1 = default).", defaultValue:"1" },
  { key:"Gr/{Name}/IncludeAxes", type:"b", namespace:"Gr",
    description:"Draw the X/Y/Z coordinate axes.", defaultValue:"False" },
  { key:"Gr/{Name}/AxesSize", type:"d", namespace:"Gr", units:"Length",
    description:"Length of the coordinate axes.", defaultValue:"1 m" },
  { key:"Gr/{Name}/HiddenLineRemovalForTrajectories", type:"b", namespace:"Gr",
    description:"Enable hidden-line removal when drawing trajectories.", defaultValue:"False" },
  { key:"Gr/{Name}/ColorBy", type:"s", namespace:"Gr",
    description:"Colour trajectories by this attribute.",
    allowedValues:["Charge","ParticleType","OriginVolume","OriginComponent",
                   "CreatorProcess","Energy","Momentum","Generation"] },
  { key:"Gr/{Name}/CenterOn", type:"s", namespace:"Gr",
    description:"Centre the camera view on a named component (e.g. 'World')." },
  { key:"Gr/{Name}/IncludeStepPoints", type:"b", namespace:"Gr",
    description:"Draw individual step points along trajectories.", defaultValue:"False" },
  { key:"Gr/Enable", type:"b", namespace:"Gr",
    description:"Enable the graphical visualisation system.", defaultValue:"True" },
  { key:"Gr/RefreshEvery", type:"s", namespace:"Gr",
    description:"When to refresh the visualisation display.",
    allowedValues:["Run","History"], defaultValue:"Run" },
  { key:"Gr/ShowOnlyOutlineIfVoxelCountExceeds", type:"i", namespace:"Gr",
    description:"Show only the outer envelope of volumes with more voxels than this.",
    defaultValue:"8000" },
  { key:"Gr/Verbosity", type:"i", namespace:"Gr",
    description:"Verbosity level for the graphics system.", defaultValue:"0" },

  // ── Tf/ ───────────────────────────────────────────────────────────────────
  { key:"Tf/NumberOfSequentialTimes", type:"i", namespace:"Tf",
    description:"Number of time slices (dwell positions, motion steps) in the run.",
    defaultValue:"1" },
  { key:"Tf/RandomizeTimeDistribution", type:"b", namespace:"Tf",
    description:"Randomise the order of time slices.", defaultValue:"False" },
  { key:"Tf/TimelineEnd", type:"d", namespace:"Tf", units:"Time",
    description:"End time of the timeline.", defaultValue:"0 s" },
  { key:"Tf/TimelineStart", type:"d", namespace:"Tf", units:"Time",
    description:"Start time of the timeline.", defaultValue:"0 s" },
  { key:"Tf/Verbosity", type:"i", namespace:"Tf",
    description:"Verbosity level for time features.", defaultValue:"0" },
  { key:"Tf/{Name}/Function", type:"s", namespace:"Tf",
    description:"Time function type.",
    allowedValues:["Step","Linear","Sine","Cosine","Gaussian"] },
  { key:"Tf/{Name}/Times", type:"dv", namespace:"Tf", units:"Time",
    description:"Time values at which the function changes (Step function)." },
  { key:"Tf/{Name}/Values", type:"dv", namespace:"Tf",
    description:"Values corresponding to each time step." },
  { key:"Tf/{Name}/RepetitionInterval", type:"d", namespace:"Tf", units:"Time",
    description:"Period for repeating the time function." },
];

// Lookup maps
export const PARAM_MAP = new Map<string, TopasParam>(
  TOPAS_PARAMS.map(p => [p.key.toLowerCase(), p])
);

export const PARAMS_BY_NAMESPACE = new Map<string, TopasParam[]>();
for (const p of TOPAS_PARAMS) {
  const list = PARAMS_BY_NAMESPACE.get(p.namespace) ?? [];
  list.push(p);
  PARAMS_BY_NAMESPACE.set(p.namespace, list);
}
